/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useLayoutEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_2_1: THREE.Mesh
  }
  materials: {
    material: THREE.MeshStandardMaterial
    Materiais: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Lata(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/lata-nova7.glb?v=2') as GLTFResult

  useLayoutEffect(() => {
    Object.values(materials).forEach((material) => {
      if (material.map) {
        material.map.flipY = false
        material.map.colorSpace = THREE.SRGBColorSpace
      }
      if (material.normalMap) material.normalMap.flipY = false
      if (material.roughnessMap) material.roughnessMap.flipY = false

      material.needsUpdate = true
    })
  }, [materials])

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_2_1.geometry} material={materials.Materiais} />
      </group>
    </group>
  )
}

useGLTF.preload('/lata-nova7.glb?v=2')
